#!/bin/bash

# Check if enough arguments are provided
if [ $# -lt 29 ]; then
    echo "Usage: $0 <namespace> <repo-name> <container-maker-host> <container-maker-port> <container-maker-certs-secret-name> <cert-manager-cron-job-name> <auth-redirect-base-uri> <google-client-id> <google-client-secret> <github-client-id> <github-client-secret> <redis-host> <redis-port> <redis-password> <redis-username> <redis-db> <postgres-host> <postgres-port> <postgres-user> <postgres-password> <postgres-db> <socket-ssh-host> <socket-ssh-wss-url> <ingress-host> <cookie-secure> <cookie-samesite> <payment-gateway-host> <payment-gateway-port> <payment-gateway-certs-secret-name>"
    exit 1
fi

YAML=./infra/deployment/deployment.yaml
NAMESPACE=$1
REPO_NAME=$2
CONTAINER_MAKER_HOST=$3
CONTAINER_MAKER_PORT=$4
CONTAINER_MAKER_CERTS_SECRET_NAME=$5
CERT_MANAGER_CRON_JOB_NAME=$6
AUTH_REDIRECT_BASE_URI=$7
GOOGLE_CLIENT_ID=$8
GOOGLE_CLIENT_SECRET=$9
GITHUB_CLIENT_ID=${10}
GITHUB_CLIENT_SECRET=${11}
REDIS_HOST=${12}
REDIS_PORT=${13}
REDIS_PASSWORD=${14}
REDIS_USERNAME=${15}
REDIS_DB=${16}
POSTGRES_HOST=${17}
POSTGRES_PORT=${18}
POSTGRES_USER=${19}
POSTGRES_PASSWORD=${20}
POSTGRES_DB=${21}
SOCKET_SSH_HOST=${22}
SOCKET_SSH_WSS_URL=${23}
INGRESS_HOST=${24}
COOKIE_SECURE=${25}
COOKIE_SAMESITE=${26}
PAYMENT_GATEWAY_HOST=${27}
PAYMENT_GATEWAY_PORT=${28}
PAYMENT_GATEWAY_CERTS_SECRET_NAME=${29}

export NAMESPACE=$NAMESPACE
export REPO_NAME=$REPO_NAME
export CONTAINER_MAKER_HOST=$CONTAINER_MAKER_HOST
export CONTAINER_MAKER_PORT=$CONTAINER_MAKER_PORT
export CONTAINER_MAKER_CERTS_SECRET_NAME=$CONTAINER_MAKER_CERTS_SECRET_NAME
export CERT_MANAGER_CRON_JOB_NAME=$CERT_MANAGER_CRON_JOB_NAME
export PAYMENT_GATEWAY_HOST=$PAYMENT_GATEWAY_HOST
export PAYMENT_GATEWAY_PORT=$PAYMENT_GATEWAY_PORT
export PAYMENT_GATEWAY_CERTS_SECRET_NAME=$PAYMENT_GATEWAY_CERTS_SECRET_NAME
export AUTH_REDIRECT_BASE_URI=$AUTH_REDIRECT_BASE_URI
export GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
export GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
export GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
export GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
export REDIS_HOST=$REDIS_HOST
export REDIS_PORT=$REDIS_PORT
export REDIS_PASSWORD=$REDIS_PASSWORD
export REDIS_USERNAME=$REDIS_USERNAME
export REDIS_DB=$REDIS_DB
export POSTGRES_HOST=$POSTGRES_HOST
export POSTGRES_PORT=$POSTGRES_PORT
export POSTGRES_USER=$POSTGRES_USER
export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
export POSTGRES_DB=$POSTGRES_DB
export SOCKET_SSH_HOST=$SOCKET_SSH_HOST
export SOCKET_SSH_WSS_URL=$SOCKET_SSH_WSS_URL
export INGRESS_HOST=$INGRESS_HOST
export COOKIE_SECURE=$COOKIE_SECURE
export COOKIE_SAMESITE=$COOKIE_SAMESITE
envsubst < $YAML | kubectl apply -f -
